### ISSUE TITLE
remote file test xhr-020 should fail when CORS is not supported

### ISSUE THREAD

**Issue by whmccoy** [IDPF/epub-testsuite#34]
scripting-003.xhtml has a simple test for getting a remote file:

// try to get a remote file
                testRequest("http://idpf.org/epub/30/spec/epub30-contentdocs.html", "xhr-030-result");                
            };

It indicates "PASS" on Readium but IMO it should fail because the http header for that URL does not presently return the CORS specified value:
Access-Control-Allow-Origin: *
Running scripting-003.xhtml standalone in a browser for example returns "FAIL" even though of course the browser supports remote file access.

I'm not sure it's explicitly defined anywhere in EPUB 3.0 specs (perhaps a spec issue!) but I believe that the EPUB file's internal relative URL space is implicitly the origin and that requests external to that should therefore be enabled only via CORS.

This implies that this test should probably fork into two variants, one that makes a request to a known CORS-enabled URL that is expected to PASS and one that makes a request to a known non-CORS-enabled URL that is expected to FAIL.

**Comment by mattgarrish** [comment]
XHR test has been updated. Fails now when requesting from a server without cors headers set (idpf), including testing from local browser.
