### ISSUE TITLE
need test for  remote access via JSONP

### ISSUE THREAD

**Issue by whmccoy** [IDPF/epub-testsuite#35]
The file scripting-003.xhtml has a test for reading remote resource via XMLHttpRequest. But in the context of EPUB remote resources will always be from a server in a different domain, since the EPUB package itself constitutes the implicit domain (relative URL space). So in addition to testing XMLHttpRequest, which requires servers with CORS support, the alternative JSONP technique should be tested, as this pre-CORS workaround still widely used in various JS libraries.

**Comment by mattgarrish** [comment]
added jsonp-010 test to a new -007 file in the -0102 scripting publication to test remote data calls.
