### ISSUE TITLE
[OPTIONAL FEATURE] Add 'Alternate Style Tags' Tests (EPUB 3.0.1)

### ISSUE THREAD

**Issue by vincent-gros** [IDPF/epub-testsuite#62]
[Alternate Style Tags](http://www.idpf.org/epub/altss-tags/) is part of EPUB 3.0.1 (see [CONTENT DOCUMENT 3.0.1](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-alternate-style-tags)).

There are three known examples in the IDPF EPUB3 Samples project:
* [wasteland](https://code.google.com/p/epub-samples/wiki/SamplesListing#wasteland) (`day` and `night` values);
* [kusamakura](https://code.google.com/p/epub-samples/wiki/SamplesListing#kusamakura-japanese-vertical-writing) (`vertical` and `horizontal` values);
* [mymedia_lite](https://code.google.com/p/epub-samples/wiki/SamplesListing#mymedia_lite) (`vertical` and `horizontal` values).

**Comment by mgylling** [comment]
@vincent-gros, we are going an update to the test suite during february, target to release in March. Would you be willing to contribute a test file for Alternate Style Tags? Note that the author-supplied CSS must be simple to distinguish from RS-supplied CSS (for example by giving the author-supplied one a really weird color...)

**Comment by vincent-gros** [comment]
@mgylling I can do it the last two weeks of February, is it ok for you?

**Comment by mgylling** [comment]
Hi Vincent,
yes that would be perfectly ok. Thanks a lot for making time for this!

/markus
