### ISSUE TITLE
include more text in FXL tests

### ISSUE THREAD

**Issue by marisademeglio** [IDPF/epub-testsuite#67]
• Fixed layout test: It is very difficult to ascertain whether fixed layout is functional when the only thing on the screen is the page number. Including a bit more on each screen (even just some "lorem ipsum" text), especially if it were vertically centered, would be extremely helpful.

**Comment by mattgarrish** [comment]
Add some placeholder text to tests 201-211.

Files -003 through -006 are duplicated from 201-210 (not 211) if you want to make additional changes and propagate quickly.
