### ISSUE TITLE
MO test basic-010 should be simpler

### ISSUE THREAD

**Issue by marisademeglio** [IDPF/epub-testsuite#69]
Current wording: 
“If there is a play/pause button that starts playing audio narration for the text on this page, then the Reading System supports Media Overlays (MO). Implied in this test is that the Reading System still recognizes MO even when the first chapter of the book does not contain it.”

Proposed change:
Remove reference to user controls as some reading systems support MO by automatically playing them (no controls though). Add another test to report whether the user has control over basic playback (stop/start).

**Comment by pettarin** [comment]
I agree. I propose what follows:

Current:

> If there is a play/pause button that starts playing audio narration for the text on this page, then the Reading System supports Media Overlays (MO).

Proposed:

> If audio rendition is started automatically after this page has been rendered, or if there is a play/pause button that starts playing audio narration for the text on this page, then the Reading System supports Media Overlays (MO).

Rationale: I was not able to locate the point of the EPUB 3 MO specification where a "play/pause button" (or other visual control) is required/recommended, albeit that is a common choice. If I am wrong on this one, please disregard this issue (and maybe reference the point in the specs that I have overlooked, thank you.)
