### ISSUE TITLE
Test 0102 (Scripting Tests): xhr-030 False positive due to bad test

### ISSUE THREAD

**Issue by pettarin** [IDPF/epub-testsuite#76]
Current: the possibility of opening remote files via XHR is deemed available with the following code:

```
 request.onload = function() {
   txt = request.responseText;
   if (txt) {
     document.getElementById(testResultId).innerHTML = 'PASS';
   }
```

In other words, as soon as `txt` is truthy, the test PASSes.

This means that if the Reading System returns a spurious string in `request.responseText` (e.g., Cordova returns `ERROR whitelist rejection: $URL` if the requested URL is not in the app whitelist) the test PASSes, albeit the Reading System did not actually access the remote file.

Proposed: probing the response code instead, or -- even better -- testing against a precise (known a priori) value for `txt`, containing the expected text of the remote file.

Rationale: avoid false positives.

**Comment by OriIdan** [comment]
The best way would be a known file.
