### ISSUE TITLE
handheld media tests

### ISSUE THREAD

**Issue by mgylling** [IDPF/epub-testsuite#87]
scripsit garth conboy: 

I think some of the @media tests are in need of tuning.

The definition of "handheld" is so wishy washy ("typically small screen and low bandwidth") that I think this test should just be removed.  At the very least the instructions for grading the test should become "If the preceding paragraph reads FAIL when displayed on a device considered a handheld, this test fails."

For TV, the definition of the device may be clearer, but the criteria for passing is wrong -- the instructions for grading the test should be "If the preceding paragraph reads FAIL when displayed on a TV device, this test fails."

Similarly the instructions for grading the portrait and landscape tests need to be fixed to be orientation-specific:

"If the preceding paragraph reads FAIL when displayed in portrait orientation, this test fails." and:

"If the preceding paragraph reads FAIL when displayed in landscape orientation, this test fails."

Best,
   Garth

**Comment by mattgarrish** [comment]
Tests have been updated to remove these ambiguities and more generally test support for media type names/queries.
